name: vccsim
channels:
    - nvidia
    - conda-forge
    - defaults
dependencies:
    - cuda=12.8
    - python=3.11
    - pip:
        - tqdm
        - plyfile
        - open3d
        - lpips
        - mediapy
        - opencv-python